[
    {"label": "eBay", "url":"https://ebay.de/"},
    {"label": "GitHub", "url":"https://github.com"},
    {"label": "G_COM", "url":"https://google.com", "group":"Google"},
    {"label": "Google News", "url":"https://news.google.de"},
    {"label": "Docker", "url":"https://www.docker.com"},
    {"label": "MyDealz", "url":"https://www.mydealz.de"},
    {"label": "G_DE", "url":"https://google.de", "group":"Google"},
    {"label": "Banggood", "url":"http://www.banggood.com"},
    {"label": "Chefkoch", "url":"http://www.chefkoch.de", "group": "Essen"},
    {"label": "Essen&Trinken", "url":"http://www.essen-und-trinken.de", "group":"Essen"},
    {"label": "Lecker.de", "url":"http://www.lecker.de", "group":"Essen"},
    {"label": "AfD", "url":"https://www.alternativefuer.de"},
    {"label": "CDU", "url":"https://cdu.de"},
    {"label": "Otto", "url":"https://www.otto.de"},
    {"label": "tagesschau", "url":"http://www.tagesschau.de"},
    {"label": "React", "url":"https://facebook.github.io/react/"},
    {"label": "Vue", "url":"https://vuejs.org"},
    {"label": "YP", "url":"http://www.youporn.com", "group": "Erotik"},
    {"label": "PH", "url":"http://www.pornhub.com", "group":"Erotik"},
    {"label": "RT", "url":"http://www.redtube.com", "group":"Erotik"},
    {"label": "Golem", "url":"http://www.golem.de"},
    {"label": "Heise", "url":"https://www.heise.de/"},
    {"label": "YouTube", "url":"https://www.youtube.com"},
    {"label": "Eatsmarter", "url":"http://eatsmarter.de", "group": "Essen"},
    {"label": "Urlaubspiraten", "url":"https://www.urlaubspiraten.de"}
]